export  'package:bentzip/Teacher/presentation/screens/teacher_notice.dart';
export 'package:bentzip/Admin/presentation/screens/about_us.dart';
export 'package:bentzip/Admin/presentation/screens/account.dart';
export 'package:bentzip/Admin/presentation/screens/activitie.dart';
export 'package:bentzip/Admin/presentation/screens/application_approval.dart';
export 'package:bentzip/Admin/presentation/screens/contact.dart';
export 'package:bentzip/Admin/presentation/screens/cooridnates_screen.dart';
export 'package:bentzip/Admin/presentation/screens/dashboard.dart';
export 'package:bentzip/Admin/presentation/screens/inventory.dart';
export 'package:bentzip/Admin/presentation/screens/loginscreen.dart';
export 'package:bentzip/Admin/presentation/screens/notice.dart';
export 'package:bentzip/Admin/presentation/screens/syllabus.dart';
export 'package:bentzip/Admin/presentation/screens/teacher_screen.dart';
export 'package:bentzip/MainScreen/screens/selection_screen.dart';
export 'package:bentzip/Teacher/presentation/screens/attendance_list/attd_student_list.dart';
export 'package:bentzip/Teacher/presentation/screens/teacher_attendance.dart';
export 'package:bentzip/Teacher/presentation/screens/teacherdashboard.dart';
export 'package:flutter/material.dart';

